name = input("Enter ur name: ")
city = input("Enter ur city: ")
fav_food = input("fav food: ")
fav_movie = input("fav movie: ")
fav_actor = input("fav actor: ")
fav_actress = input("fav actress: ")
fav_author = input("fav author: ")
fav_singer = input("fav singer: ")
fav_song = input("fav song: ")
fav_sports = input("fav sports: ")
fav_sportsman = input("fav sportsman: ")
fav_dog = input("fav dog breed: ")

print("!!!!INFO!!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_movie=}')
print(f'{fav_actor=}')
print(f'{fav_actress=}')
print(f'{fav_author=}')
print(f'{fav_singer=}')
print(f'{fav_song=}')
print(f'{fav_sports=}')
print(f'{fav_sportsman=}')
print(f'{fav_dog=}')
print("!!!!INFO!!!!")   